name: Pushing to the staging server

on:
  push:
    branches:
      - release/staging
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Remove vendor directory
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.WORKING_DIR }}
            [ -d ./vendor ] && rm -rf ./vendor
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.USER_PRIVATE_KEY }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --no-dev

      - name: Create zipped vendor directory
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./vendor.zip ./vendor

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://${{ secrets.ADDRESS_URL }}/
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}

  post-deploy:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Run migrations and seeders, clear cache for views, config and routes
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.WORKING_DIR }}
            unzip -qq ./vendor.zip
            rm -f vendor.zip
            php artisan config:clear
            php artisan view:clear
            php artisan route:cache
          host: ${{ secrets.SERVER_IP }}
          user:	${{ secrets.SSH_USER }}
          key: ${{ secrets.USER_PRIVATE_KEY }}
