name: Deply to Heroku

on:
  push:
    branches:
      - release/staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "fac-lumen-api"
          useforce: true
          dynamicFiles: true
          procfile: "web: vendor/bin/heroku-php-apache2 public/"
          buildpacks: ['https://github.com/heroku/heroku-buildpack-php.git']